services:
  app:
    container_name: kanban-api
    build:
      context: .
    env_file:
      - .env
    volumes:
      - /app/src
    ports:
      - 3000:3000
      - 5555:5555
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: pg_kanban
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
